# -*- coding: utf-8 -*-
"""Dataminig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14s0M9-mTQZeuDJJxplWy8G0YeFZRLaDz

Import the Dependencies
"""

import numpy as np
import pandas as pd
from prophet import Prophet

"""Data collection and pre-processing

Dataset link : https://archive.ics.uci.edu/dataset/360/air+quality

CSV file link : https://drive.google.com/file/d/1qMuYPYMrQ3gDZBCD07NNJu9lPG34hdba/view?usp=sharing
"""

# Loading data from csv file to panda dataset
air_quality_data = pd.read_csv('AirQualityUCI.csv', sep=";", decimal=',')

# Removing redundant columns
air_quality_data = air_quality_data.iloc[:, :-2]

# Take first 9357 rows alone from the dataframe
air_quality_data = air_quality_data.head(9357)

# Converting -200 to NaN
air_quality_data = air_quality_data.replace(to_replace=-200, value=np.NaN)

# Fill missing values with the mean of each column for columns 3 to 15
air_quality_data.iloc[:, 2:] = air_quality_data.iloc[:, 2:].fillna(air_quality_data.iloc[:, 2:].mean())

# Converting date format to YYYY-MM-DD
data_info = pd.to_datetime(air_quality_data['Date'], format='%d/%m/%Y')
time_info = air_quality_data['Time'].apply(lambda x: x.replace('.', ':'))

# Combining date and time
date_time = pd.concat([data_info, time_info], axis=1)
date_time.columns = ['Date', 'Time']

# Formatting datetime
date_time['ds'] = pd.to_datetime(date_time['Date'].astype(str) + ' ' + date_time['Time'].astype(str))

# Creating Prophet compatible DataFrame
data = pd.DataFrame({'ds': date_time['ds'], 'y': air_quality_data['RH']})

# Fit Prophet model
m = Prophet()
m.fit(data)

# Make future predictions
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)

# Plotting
fig1 = m.plot(forecast)
fig2 = m.plot_components(forecast)
